In [19]:
import pandas as pd
df = pd.read_csv('GreenThumb_Garden_Info.csv')
df

,assemblydist,borough,communityboard,congressionaldist,coundist,gardenname,juris,multipolygon,openhrsf,openhrsm,openhrssa,openhrssu,openhrsth,openhrstu,openhrsw,parksid,policeprecinct,statesenatedist,status,zipcode
0,53,B,301,7,34,Sunshine Community Garden,DPR,MULTIPOLYGON (((-73.94412030988389 40.70541945...,12:00p - 4:00p,NaN,2:00p - 6:00p,11:00a - 3:00p,NaN,NaN,NaN,B427-GT001,90,18,Active,11206
1,53,B,301,7,34,Moore Street Farm,DPR,MULTIPOLYGON (((-73.94124763864957 40.70353535...,2 p.m. to 6 p.m.,NaN,1 p.m. to 6 p.m.,1 p.m. to 6 p.m.,NaN,NaN,NaN,B545-GT001,90,18,Inactive (Group Forming),11206
2,68,M,111,13,8,Olga's El Gallo Community Garden,DPR,MULTIPOLYGON (((-73.94071467019982 40.79969950...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M392-GT001,25,30,Active,10035
3,57,B,302,10,35,MoCADA Ubuntu Garden,PRI,MULTIPOLYGON (((-73.9769461625688 40.686880484...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BGT177,88,26,Active,11217
4,55,B,316,8,41,Eden Community Garden,DPR,MULTIPOLYGON (((-73.91592305902948 40.67570857...,NaN,3:00p - 6:00p,NaN,11:00a - 3:00p,3:00p - 6:00p,NaN,3:00p - 6:00p,B476-GT001,73,25,Active,11233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,29,Q,412,5,27,Senior Citizen Garden Club,DPR,MULTIPOLYGON (((-73.77112451557377 40.68779304...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q448-GT001,113,14,Not GreenThumb,11434
609,56,B,308,9,36,Garden Kitchen Lab at St. John's Rec.,DPR,MULTIPOLYGON (((-73.93500081856017 40.67391829...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B245-GT001,77,20,Not GreenThumb,11213
610,56,B,303,8,36,Von King Park and Cultural Center Garden,DPR,MULTIPOLYGON (((-73.9469681111235 40.689049288...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B088-GT001,79,25,Not GreenThumb,11216
611,69,M,107,12,6,Garden People,DPR,MULTIPOLYGON (((-73.97899093812129 40.79309028...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M071-GT001,24,47,Not GreenThumb,10024
612,53,B,301,7,34,Orient Grove,DPR,MULTIPOLYGON (((-73.9401510777611 40.714941641...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B024-GT001,90,18,Not GreenThumb,11211

In [20]:
df.drop(columns='multipolygon', inplace=True)

In [23]:
active_g = df[df['status'].str.contains('Active')]
len(active_g)
#There are at least 541 active gardens in NYC.

541

In [12]:
#NYC population per 2020 census is 8773000 
(541 / 8773000 * 100000)
#6.2 per 100000 people in NYC has access to a community garden

6.166647668984384

In [24]:
active_g_borough = active_g.borough.value_counts()
active_g_borough.to_csv('Active garden by borough.csv')
#Brooklyn: 238 gardens
#Manhattan: 138 gardens
#Bronx: 115 gardens
#Queens: 43 gardens
#State Island: 7 gardens

In [17]:
active_g = df[df['status'].str.contains('Active')]
active_g_zipcode = active_g.zipcode.value_counts()
active_g_zipcode.to_csv('active_garden_by_zipcode.csv')
# 11207 (East New York, Brooklyn): 44
# 10009 (East Village, Manhattan): 38
# 11233 (Ocean Hill, Brooklyn): 26
# 11221 (Bushwick, Brooklyn): 21
# 10027 (Manhattanville, Manhattan): 20
# 11206 (Bushwick, Brooklyn): 19
# 11208 (East New York, Brooklyn): 19
# 11212 (Brownsville, Brooklyn): 17
# 10035 (East Harlem, Manhattan): 17
# 10456 (Concourse, Bronx): 17

NameError: name 'df' is not defined

In [128]:
active_g.juris.value_counts()
#show the top 10 entities that own the community gardens
# DPR (Department of Parks and Recreation): 359
# NYRP (New York Restoration Project): 48
# BQLT (Brooklyn Queens Land Trust Inc): 35
# NYCHA (New York City Housing Authority): 20
# BLT (Bronx Land Trust): 17
# MLT (Manhattan Land Trust): 12
# PRI: 12
# DOT (Dept of Transportation): 8
# BANG (Brooklyn Alliance of Neighborhood Gardens): 5
# DEP (Dept of Environmental Protection): 4

juris
DPR          359
NYRP          48
BQLT          35
NYCHA         20
BLT           17
MLT           12
PRI           12
DOT            8
BANG           5
DEP            4
MTA            4
DPR/PRI        3
DPR/MLT        2
JOP            2
NYPD           2
DCAS           1
NYSDOT         1
DPR/MTA        1
MTA/BQLT       1
DPR/NYRP       1
PRI / DOT      1
DOE            1
DPR/FDNY       1
Name: count, dtype: int64

In [99]:
active_garden.groupby('borough').juris.value_counts()
#show the entities that own the community gardens by borough.

borough  juris
B        DPR          163
         BQLT          28
         NYRP          20
         NYCHA          8
         BANG           5
         PRI            4
         DEP            3
         DCAS           1
         DOT            1
         DPR/PRI        1
         MTA            1
         MTA/BQLT       1
         NYPD           1
         NYSDOT         1
M        DPR           97
         MLT           12
         NYRP          11
         PRI            4
         NYCHA          3
         DPR/PRI        2
         JOP            2
         DOT            2
         DPR/MLT        2
         DPR/NYRP       1
         DEP            1
         DPR/FDNY       1
Q        DPR           25
         BQLT           7
         NYRP           3
         DOT            2
         NYCHA          2
         MTA            2
         DOE            1
         PRI            1
R        DPR            3
         PRI / DOT      1
         PRI            1
         NYRP           1
         NYPD           1
X        DPR           71
         BLT           17
         NYRP          13
         NYCHA          7
         DOT            3
         PRI            2
         MTA            1
         DPR/MTA        1
Name: count, dtype: int64

In [106]:
active_garden.groupby('borough').communityboard.value_counts()
#community board for each borough with the most number of community gardens
#Brooklyn 303: 59
#Manhattan 103: 47
#Queens 412: 15
#Staten Island 501: 7
#Bronx 201: 26

borough  communityboard
B        303               59
         305               56
         316               29
         301               18
         304               18
         306               14
         302               14
         308               11
         307                4
         318                4
         309                3
         313                3
         314                2
         315                1
         317                1
         201                1
M        103               47
         111               32
         110               31
         109               15
         112                4
         107                4
         104                2
         102                2
         101                1
Q        412               15
         414                9
         402                5
         401                3
         403                3
         404                2
         413                2
         411                1
         407                1
         406                1
         405                1
R        501                7
X        201               26
         203               19
         204               18
         206               16
         202                9
         205                7
         209                6
         207                5
         212                5
         210                2
         211                1
         208                1
Name: count, dtype: int64

In [129]:
inactive_g = df[df['status'].str.contains('Inactive')]
len(inactive_g)
#There are at least 16 inactive gardens.

16

In [130]:
inactive_g.borough.value_counts()
#inactive garden count by borough
#Brooklyn: 5
#Manhattan: 4
#Queens: 4
#Bronx: 3
#Staten Island: 0

borough
B    5
M    4
Q    4
X    3
Name: count, dtype: int64

In [131]:
inactive_g.juris.value_counts()
#DPR: 11
#NYCHA: 4
#NYRP: 1

juris
DPR      11
NYCHA     4
NYRP      1
Name: count, dtype: int64

In [132]:
inactive_g.zipcode.value_counts()

zipcode
10029    2
11206    1
10465    1
10456    1
11201    1
10027    1
11691    1
11212    1
11207    1
11434    1
10451    1
10035    1
11412    1
11436    1
11208    1
Name: count, dtype: int64